### ISSUE TITLE
Normalize news/video teasers on home page

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#70]
Mainly typography

![Screen Shot 2019-10-15 at 1 59 50 PM](https://user-images.githubusercontent.com/36719/67045170-9b486980-f0e2-11e9-91e7-29a40daf6014.png)
![Screen Shot 2019-10-15 at 1 59 54 PM](https://user-images.githubusercontent.com/36719/67045171-9b486980-f0e2-11e9-89ce-137c917d1425.png)

**Comment by Herm71** [comment]
I don't see much difference in the typography on these two images but I do see that there's different padding/margins on each of them on the site, so I guess that's what this issue is about? I'll make sure the padding/margins are consistent and if they still need more work, we can start a new issue.

**Comment by Herm71** [comment]
Ok, I see what happened:
![Selection_001](https://user-images.githubusercontent.com/1000543/67607943-193bee80-f73b-11e9-8486-8481ff05b781.png)
